version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./code:/app
      - /app/node_modules  # Prevent host/node_modules interference
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=5173
      - VITE_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3